import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";

const inter = Cinzel({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-6xl mx-auto p-4 bg-black">
          {children}
        </main>
      </body>
    </html>
  );
}
